FROM ghcr.io/downunderctf/docker-vendor/nsjail:ubuntu-22.04

ENV JAIL_CWD=/chal
COPY ./flag-rev.txt /home/ctf/chal/flag-rev.txt
COPY ./flag-pwn.txt /home/ctf/chal/flag-pwn.txt
COPY ./ezpz /home/ctf/chal/pwn
